# Generated by Django 4.1.7 on 2023-04-04 03:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('soda_product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soda_product',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
